'use strict';

/**
 * Shared constant values mirroring the Prisma enums plus
 * cross-cutting strings used across modules.
 */

const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  CLINIC_ADMIN: 'CLINIC_ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PATIENT: 'PATIENT',
});

const APPOINTMENT_STATUS = Object.freeze({
  HOLD: 'HOLD',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

const PLAN_TIER = Object.freeze({
  BASIC: 'BASIC',
  PRO: 'PRO',
  ENTERPRISE: 'ENTERPRISE',
});

const SUBSCRIPTION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELLED: 'CANCELLED',
  TRIALING: 'TRIALING',
});

const NOTIFICATION_TYPE = Object.freeze({
  APPOINTMENT: 'APPOINTMENT',
  PAYMENT: 'PAYMENT',
  SYSTEM: 'SYSTEM',
});

/** Stable strings written to AuditLog.action */
const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOCKED: 'USER_LOCKED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  CLINIC_CREATED: 'CLINIC_CREATED',
  STAFF_CREATED: 'STAFF_CREATED',
  APPOINTMENT_HELD: 'APPOINTMENT_HELD',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  RECORD_CREATED: 'RECORD_CREATED',
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  SUBSCRIPTION_CHANGED: 'SUBSCRIPTION_CHANGED',
});

const ROLE_LIST = Object.values(ROLES);

module.exports = {
  ROLES,
  ROLE_LIST,
  APPOINTMENT_STATUS,
  PAYMENT_STATUS,
  PLAN_TIER,
  SUBSCRIPTION_STATUS,
  NOTIFICATION_TYPE,
  AUDIT_ACTIONS,
};
